SAVE_ROOT = "my_data/"
DATA_ROOT = "../../fiot_highway2-main/data/"
TRAIN_TXT = "../../fiot_highway2-main/train.txt"
TEST_TXT  = "../../fiot_highway2-main/test.txt"
LOGS_ROOT = "logs"
LABELS = {0,1,2,3,4,5,6,7,8}
SPECTO_SHAPE = (512, 243) #(row, col)
SPECTO_MAX = 0 #dB
SPECTO_MIN = -136 #dB
